#!/bin/bash
 
cmake \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DCMAKE_SKIP_INSTALL_RPATH:BOOL=YES \
  -DBUILD_TESTING:BOOL=OFF \
  -DPARAVIEW_BUILD_QT_GUI:BOOL=OFF \
  -DVTK_RENDERING_BACKEND=OpenGL2 \
  -DPARAVIEW_USE_MPI:BOOL=ON \
  -DPARAVIEW_ENABLE_PYTHON:BOOL=ON \
  -DPARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON \
  -DPARAVIEW_BUILD_CATALYST_ADAPTERS:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_AnalyzeNIfTIIO:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_ArrowGlyph:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_CDIReader:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_EyeDomeLighting:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_GMVReader:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_GeodesicMeasurement:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_H5PartReader:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_InSituExodus:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_MantaView:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_Moments:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_NonOrthogonalSource:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_PacMan:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_PointSprite:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_RGBZView:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_SLACTools:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_SciberQuestToolKit:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_SierraPlotTools:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_StreamingParticles:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_SurfaceLIC:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_ThickenLayeredCells:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_UncertaintyRendering:BOOL=FALSE \
  -DPARAVIEW_BUILD_PLUGIN_AcceleratedAlgorithms:BOOL=OFF \
  -DVTK_USE_CXX11_FEATURES:BOOL=ON \
  -DCMAKE_INSTALL_PREFIX=/home/neal/software/ParaView_osMesa \
  -DPARAVIEW_BUILD_QT_GUI=OFF \
  -DVTK_USE_X=OFF \

  -DOPENGL_INCLUDE_DIR=/home/neal/software/Mesa/build/include \
  -DOPENGL_gl_LIBRARY=/home/neal/software/Mesa/build/lib64/libOSMesa.so \
  -DOPENGL_glu_LIBRARY=/home/neal/software/Mesa/build/lib64/libGLU.so \
  -DVTK_OPENGL_HAS_OSMESA=ON \
  -DOSMESA_INCLUDE_DIR=/home/neal/software/Mesa/build/include \
  -DOSMESA_LIBRARY=/home/neal/software/Mesa/build/lib64/libOSMesa.so \
  /home/neal/software/ParaView
 
make -j20
make -j20 install
